[package]
name = "graphy"
version = "0.1.0"
edition = "2021"

[dependencies]
auto_ops = "0.3.0"
itertools = "0.12.0"
rand = "0.8.5"
rand_distr = "0.4.3"
fix_fn = "1.0.2"
utc-dt = "0.3.0"
clap = { version = "4.5.28", features = ["derive"] }
rayon = "1.10.0"

